# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
