# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180727_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100)),
                ('nurse', models.CharField(max_length=100)),
                ('reception', models.CharField(max_length=100)),
            ],
        ),
    ]
